### ISSUE TITLE
Warning on composer update command

### ISSUE THREAD

**Issue by hasnatbabur** [nscreed/laravel-migration-paths#2]
Deprecation Notice: Class NsCreed\MigrationPath\InvalidPathException located in ./vendor/nscreed/laravel-migration-paths/src/Exceptions/InvalidPathException.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by nscreed** [comment]
@hasnatbabur Thank you for reporting the issue. The issue has been resolved, you can use the new version. It is now compatible with Laravel 5.5, 6, and 7.
