### ISSUE TITLE
i got this error

### ISSUE THREAD

**Issue by abbasfisal** [nscreed/laravel-migration-paths#4]
Argument 1 passed to NsCreed\MigrationPath\CustomMigrationPaths::__construct() must be of the type array, null given, called in

**Comment by nscreed** [comment]
Hi @abbasfisal, How did you configure the migration folder? Can you let me know your configuration?

You also can publish the configuration and made the necessary changes. 

`php artisan vendor:publish --provider="NsCreed\MigrationPath\ServiceProvider" --tag="config"`
